from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
from typing import Dict, List
import os

def create_pdf_report(suspect_name: str, analytics_data: Dict, output_path: str):
    """Create comprehensive PDF report for suspect analysis"""

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )

    # Container for the 'Flowable' objects
    elements = []

    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#6366f1'),
        spaceAfter=30,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#8b5cf6'),
        spaceAfter=12,
        spaceBefore=12
    )

    # Title
    elements.append(Paragraph("CDR Intelligence Report", title_style))
    elements.append(Spacer(1, 0.2*inch))

    # Report metadata
    metadata = [
        ["Suspect Name:", suspect_name],
        ["Report Date:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Generated By:", "CDR Intelligence Platform"]
    ]

    metadata_table = Table(metadata, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
    ]))
    elements.append(metadata_table)
    elements.append(Spacer(1, 0.3*inch))

    # Executive Summary
    elements.append(Paragraph("Executive Summary", heading_style))

    summary_data = analytics_data.get('summary', {})
    summary_text = f"""
    <b>Total Records:</b> {summary_data.get('total_records', 0)}<br/>
    <b>Date Range:</b> {summary_data.get('date_range', 'N/A')}<br/>
    <b>Unique Contacts:</b> {summary_data.get('unique_contacts', 0)}<br/>
    <b>Total Call Duration:</b> {summary_data.get('total_duration_hours', 0):.2f} hours<br/>
    <b>Unique IMEIs:</b> {summary_data.get('unique_imeis', 0)}<br/>
    <b>Cell Towers Visited:</b> {summary_data.get('unique_towers', 0)}
    """
    elements.append(Paragraph(summary_text, styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))

    # IMEI Analysis
    if 'imei' in analytics_data:
        elements.append(PageBreak())
        elements.append(Paragraph("IMEI Device Analysis", heading_style))

        imei_data = analytics_data['imei']
        imei_table_data = [['IMEI', 'Usage Count', 'First Seen', 'Last Seen', 'Duration (Days)']]

        for imei_info in imei_data.get('imeis', [])[:10]:
            imei_table_data.append([
                imei_info.get('imei', 'N/A'),
                str(imei_info.get('usage_count', 0)),
                imei_info.get('first_seen', 'N/A')[:10] if imei_info.get('first_seen') else 'N/A',
                imei_info.get('last_seen', 'N/A')[:10] if imei_info.get('last_seen') else 'N/A',
                str(imei_info.get('timeline', {}).get('duration_days', 0))
            ])

        imei_table = Table(imei_table_data, colWidths=[1.5*inch, 1*inch, 1.2*inch, 1.2*inch, 1*inch])
        imei_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(imei_table)
        elements.append(Spacer(1, 0.2*inch))

    # Contact Analysis
    if 'contacts' in analytics_data:
        elements.append(PageBreak())
        elements.append(Paragraph("Contact Analysis", heading_style))

        contacts_data = analytics_data['contacts']

        # Most Called Numbers
        elements.append(Paragraph("Top 10 Most Called Numbers", styles['Heading3']))
        contacts_table_data = [['Phone Number', 'Call Count', 'Total Duration (Hours)']]

        for contact in contacts_data.get('most_called', [])[:10]:
            duration_hours = (contact.get('total_duration_seconds', 0) or 0) / 3600
            contacts_table_data.append([
                contact.get('number', 'N/A'),
                str(contact.get('call_count', 0)),
                f"{duration_hours:.2f}"
            ])

        contacts_table = Table(contacts_table_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
        contacts_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#8b5cf6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(contacts_table)
        elements.append(Spacer(1, 0.2*inch))

    # Cell Tower Analysis
    if 'towers' in analytics_data:
        elements.append(PageBreak())
        elements.append(Paragraph("Cell Tower Analysis", heading_style))

        towers_data = analytics_data['towers']
        towers_table_data = [['Tower ID', 'Usage Count', 'Latitude', 'Longitude']]

        for tower in towers_data.get('towers', [])[:15]:
            location = tower.get('location', {})
            towers_table_data.append([
                tower.get('tower_id', 'N/A'),
                str(tower.get('usage_count', 0)),
                f"{location.get('lat', 0):.6f}" if location.get('lat') else 'N/A',
                f"{location.get('lon', 0):.6f}" if location.get('lon') else 'N/A'
            ])

        towers_table = Table(towers_table_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        towers_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ec4899')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(towers_table)
        elements.append(Spacer(1, 0.2*inch))

    # SMS Service Detection
    if 'sms' in analytics_data:
        elements.append(PageBreak())
        elements.append(Paragraph("SMS Service Detection", heading_style))

        sms_data = analytics_data['sms']
        services = sms_data.get('services_detected', {})

        sms_table_data = [['Service', 'Message Count']]
        for service, info in list(services.items())[:10]:
            sms_table_data.append([
                service,
                str(info.get('count', 0))
            ])

        sms_table = Table(sms_table_data, colWidths=[3*inch, 3*inch])
        sms_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#10b981')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(sms_table)
        elements.append(Spacer(1, 0.2*inch))

    # International Calls
    if 'international' in analytics_data:
        elements.append(PageBreak())
        elements.append(Paragraph("International Calls Analysis", heading_style))

        intl_data = analytics_data['international']
        countries = intl_data.get('countries', {})

        intl_table_data = [['Country', 'Call Count', 'Total Duration (Hours)']]
        for country, stats in list(countries.items())[:15]:
            duration_hours = (stats.get('total_duration_seconds', 0) or 0) / 3600
            intl_table_data.append([
                country,
                str(stats.get('call_count', 0)),
                f"{duration_hours:.2f}"
            ])

        intl_table = Table(intl_table_data, colWidths=[2.5*inch, 1.5*inch, 2*inch])
        intl_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f59e0b')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        elements.append(intl_table)

    # Build PDF
    doc.build(elements)
    return output_path
